#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD="$(tput bold)"; DIM="$(tput dim)"; RESET="$(tput sgr0)"
  GREEN="$(tput setaf 2)"; YELLOW="$(tput setaf 3)"; BLUE="$(tput setaf 4)"; RED="$(tput setaf 1)"
else
  BOLD=""; DIM=""; RESET=""; GREEN=""; YELLOW=""; BLUE=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

_clear() {
  if [[ -t 1 ]]; then printf '\033c'; fi
}

banner() {
  _clear
  printf '%s%s%s\n\n' "$BOLD" "$1" "$RESET"
  printf '%s%s%s\n\n' "$DIM" "This wizard walks you through manual steps only you can perform." "$RESET"
}

stage() {
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  _clear
  printf '%s[%d/%d] %s%s\n\n' "$BOLD" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

say()  { printf '  %s\n' "$1"; }
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

open_url() {
  local url="$1"
  step "Opening: $url"
  if command -v open >/dev/null 2>&1; then open "$url" >/dev/null 2>&1 || true
  elif command -v xdg-open >/dev/null 2>&1; then xdg-open "$url" >/dev/null 2>&1 || true
  elif command -v wslview >/dev/null 2>&1; then wslview "$url" >/dev/null 2>&1 || true
  else note "Open this URL manually: $url"
  fi
}

pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

confirm() {
  local q="$1" ans
  printf '  %s [y/N] ' "$q"
  read -r ans || true
  [[ "$ans" =~ ^[Yy]$ ]]
}

_existing() {
  local key="$1"
  [[ -f "$ENV_FILE" ]] || return 0
  grep -m1 "^${key}=" "$ENV_FILE" 2>/dev/null | cut -d= -f2- || true
}

ask() {
  local __key="$1" prompt="$2" default input
  default="$(_existing "$__key")"
  if [[ -n "$default" ]]; then
    printf '  %s [%s]: ' "$prompt" "$default"
  else
    printf '  %s: ' "$prompt"
  fi
  read -r input || true
  if [[ -z "$input" && -n "$default" ]]; then input="$default"; fi
  printf -v "$__key" '%s' "$input"
}

ask_secret() {
  local __key="$1" prompt="$2" input
  printf '  %s: ' "$prompt"
  read -rs input || true
  printf '\n'
  printf -v "$__key" '%s' "$input"
}

write_env() {
  local key="$1" value="$2"
  touch "$ENV_FILE"
  if grep -q "^${key}=" "$ENV_FILE" 2>/dev/null; then
    local tmp; tmp="$(mktemp)"
    awk -v k="$key" -v v="$value" -F= 'BEGIN{OFS="="} $1==k{$0=k"="v} {print}' "$ENV_FILE" > "$tmp"
    mv "$tmp" "$ENV_FILE"
  else
    printf '%s=%s\n' "$key" "$value" >> "$ENV_FILE"
  fi
  WRITTEN_ENV+=("$key")
}

set_secret() {
  local name="$1" value="$2"
  if ! command -v gh >/dev/null 2>&1; then
    warn "gh CLI not found; couldn't set secret $name. Set it manually."
    SKIPPED+=("secret:$name")
    return
  fi
  if ! gh auth status >/dev/null 2>&1; then
    warn "gh not authenticated; couldn't set secret $name. Run 'gh auth login' then re-run."
    SKIPPED+=("secret:$name")
    return
  fi
  if printf '%s' "$value" | gh secret set "$name" --repo superyngo/wenget >/dev/null 2>&1; then
    WRITTEN_SECRET+=("$name")
  else
    warn "Failed to set secret $name via gh."
    SKIPPED+=("secret:$name")
  fi
}

finish() {
  _clear
  printf '%s%s%s\n\n' "$BOLD" "Done." "$RESET"
  if [[ ${#WRITTEN_ENV[@]} -gt 0 ]]; then
    printf '  Wrote to %s: %s\n' "$ENV_FILE" "${WRITTEN_ENV[*]}"
  fi
  if [[ ${#WRITTEN_SECRET[@]} -gt 0 ]]; then
    printf '  Set GitHub secrets: %s\n' "${WRITTEN_SECRET[*]}"
  fi
  if [[ ${#SKIPPED[@]} -gt 0 ]]; then
    printf '  %sSkipped (do manually): %s%s\n' "$YELLOW" "${SKIPPED[*]}" "$RESET"
  fi
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=3

banner "Widen WINGET_TOKEN scope for wenget's winget publish workflow"

# ── Stage 1: figure out token type ─────────────────────────────────────────
stage "Find your WINGET_TOKEN in GitHub"
say "publish-winget.yml uses secrets.WINGET_TOKEN to sync your winget-pkgs fork"
say "and run winget-releaser. The sync step just failed with:"
note "  refusing to allow a Personal Access Token to update workflow"
note "  .github/workflows/domain-validation-assist.lock.yml without 'workflow' scope"
say "This means the token is missing the 'workflow' scope (classic PAT) or the"
say "'Workflows' permission (fine-grained PAT)."
open_url "https://github.com/settings/tokens"
step "Find the token you use as WINGET_TOKEN in the 'Personal access tokens (classic)' list."
step "If it's NOT there, it's a fine-grained token — check https://github.com/settings/tokens?type=beta instead."
ask TOKEN_TYPE "Is it a classic token or a fine-grained token? (classic/fine-grained)"

# ── Stage 2: widen scope ────────────────────────────────────────────────────
stage "Grant the workflow permission"
if [[ "$TOKEN_TYPE" == "classic" ]]; then
  step "Click the token name to open it."
  step "Check the 'workflow' scope checkbox (this also implies 'repo' scopes needed for the fork push)."
  step "Scroll down and click 'Update token'. The token STRING DOES NOT CHANGE for a classic token."
  say "No new secret value is needed — GitHub applies the new scope to the same token immediately."
  WIDENED_IN_PLACE=1
else
  step "Click the fine-grained token used for WINGET_TOKEN."
  step "Under 'Repository access', confirm 'superyngo/winget-pkgs' (the fork) is included."
  step "Under 'Permissions' → 'Repository permissions', set 'Workflows' to 'Read and write'."
  step "Also confirm 'Contents' is 'Read and write' (needed for the branch merge/push)."
  step "Save. Fine-grained token permission changes may require regenerating the token."
  warn "If GitHub forces a regeneration, copy the NEW token value now — it's shown only once."
  ask_secret WINGET_TOKEN "Paste the token value ONLY if it changed (leave blank if unchanged):"
  WIDENED_IN_PLACE=0
fi

if [[ "${WINGET_TOKEN:-}" != "" ]]; then
  set_secret WINGET_TOKEN "$WINGET_TOKEN"
  say "Updated the WINGET_TOKEN secret on superyngo/wenget."
else
  say "Leaving the existing WINGET_TOKEN secret on superyngo/wenget unchanged (scope widened in place)."
fi

# ── Stage 3: verify ─────────────────────────────────────────────────────────
stage "Re-run the publish workflow to verify"
say "Re-dispatch publish-winget.yml for the v3.9.0 tag to confirm the sync step now succeeds."
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  if confirm "Dispatch publish-winget.yml now for tag v3.9.0?"; then
    gh workflow run publish-winget.yml --repo superyngo/wenget -f tag=v3.9.0 || warn "Dispatch failed — run it manually from the Actions tab."
    say "Check status with: gh run list --repo superyngo/wenget --workflow=publish-winget.yml --limit 3"
  else
    note "Skipped. Run manually later with:"
    note "  gh workflow run publish-winget.yml --repo superyngo/wenget -f tag=v3.9.0"
  fi
else
  note "gh not available/authenticated here. From the GitHub UI:"
  note "  Actions → Publish to winget → Run workflow → tag: v3.9.0"
fi

finish
